name: Metrics
on:
  # Schedule daily updates
  schedule: [{cron: "0 0 * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          plugin_languages: yes
          plugin_languages_indepth: yes
          plugin_languages_other: yes
          plugin_languages_limit: 8
          plugin_languages_sections: most-used
          plugin_languages_recent_load: 1000
          plugin_languages_recent_days: 365
          plugin_languages_details: bytes-size, percentage, lines
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
          plugin_lines: yes
          plugin_licenses: yes
          plugin_achievements: yes
          plugin_achievements_display: compact


